name: videosdk_room_stats
description: VideoSDK Room Stats allows you to collect Video call metrics from the videosdk library.
version: 0.0.4+F
homepage: "https://videosdk.live/"
repository: "https://github.com/videosdk-live/videosdk-rtc-flutter-sdk-example"
documentation: https://docs.videosdk.live/

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  events2: ^1.0.0
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

platforms:
  android:
  ios:
