name: videosdk_flutter_example
description: A Flutter project for VideoSDK Demonstration.

publish_to: "none"

version: 1.0.0+4
environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  videosdk:
    path: ../
  http: ^1.2.2
  flutter_dotenv: ^5.2.1
  cupertino_icons: ^1.0.8
  fluttertoast: 8.2.8
  camera: ^0.11.0
  flutter_svg:  ^2.0.10
  visibility_detector: ^0.4.0
  date_time_format: ^2.0.1
  touch_ripple_effect: ^2.5.1
  webview_flutter: ^4.10.0
  videosdk_media_effects: 0.0.2


dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/
    - prod.env